[book]
authors = ["Valentyn Yukhymenko"]
language = "en"
multilingual = false
src = "src"
title = "mdbook template"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/BaLiKfromUA/mdbook-template"